title: Experience AI Challenge Stage 4 - Make a playlist generator
hero_image: images/banner.png
description: Now you have trained your ML model, you need to test that it returns songs like the ones you specified. 

In this stage, you will create the Scratch application that will use your trained model to create a list of songs for each of your classes.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Set up in Scratch 
  - title: Set your playlist length
  - title: Search for songs
  - title: Compare songs with your model
  - title: Play back your playlist
  - title: What next?
